steps:
  # Build and Push Docker Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-west1-docker.pkg.dev/upgradlabs-1740997927286/mycontainerrg/gke-webpage:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west1-docker.pkg.dev/upgradlabs-1740997927286/mycontainerrg/gke-webpage:latest'

  # Get GKE credentials
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'autopilot-cluster-1'
      - '--region'
      - 'us-west1'
      - '--project'
      - 'upgradlabs-1740997927286'

  # Deploy application to GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'kubectl'
      - 'apply'
      - '-f'
      - 'k8s/deployment.yaml'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'kubectl'
      - 'apply'
      - '-f'
      - 'k8s/service.yaml'

  # Verify deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'kubectl'
      - 'get'
      - 'services'
      - '-o'
      - 'wide'

images:
  - 'us-west1-docker.pkg.dev/upgradlabs-1740997927286/mycontainerrg/gke-webpage:latest'
logsBucket: "gs://mybucket235dfh"


